COUNTRIES_CHOICES = [
    ('AFG', 'Afghanistan'),
    ('ALB', 'Albania'),
    ('DZA', 'Algeria'),
    ('AND', 'Andorra'),
    ('AGO', 'Angola'),
    ('ATG', 'Antigua and Barbuda'),
    ('ARG', 'Argentina'),
    ('ARM', 'Armenia'),
    ('AUS', 'Australia'),
    ('AUT', 'Austria'),
    ('AZE', 'Azerbaijan'),
    ('BHS', 'Bahamas'),
    ('BHR', 'Bahrain'),
    ('BGD', 'Bangladesh'),
    ('BRB', 'Barbados'),
    ('BLR', 'Belarus'),
    ('BEL', 'Belgium'),
    ('BLZ', 'Belize'),
    ('BEN', 'Benin'),
    ('BTN', 'Bhutan'),
    ('BOL', 'Bolivia (Plurinational State of)'),
    ('BIH', 'Bosnia and Herzegovina'),
    ('BWA', 'Botswana'),
    ('BRA', 'Brazil'),
    ('BRN', 'Brunei Darussalam'),
    ('BGR', 'Bulgaria'),
    ('BFA', 'Burkina Faso'),
    ('BDI', 'Burundi'),
    ('CPV', 'Cabo Verde'),
    ('KHM', 'Cambodia'),
    ('CMR', 'Cameroon'),
    ('CAN', 'Canada'),
    ('CAF', 'Central African Republic'),
    ('TCD', 'Chad'),
    ('CHL', 'Chile'),
    ('CHN', 'China'),
    ('COL', 'Colombia'),
    ('COM', 'Comoros'),
    ('COG', 'Congo'),
    ('CRI', 'Costa Rica'),
    ('HRV', 'Croatia'),
    ('CUB', 'Cuba'),
    ('CYP', 'Cyprus'),
    ('CZE', 'Czechia'),
    ('COD', 'Democratic Republic of the Congo'),
    ('DNK', 'Denmark'),
    ('DJI', 'Djibouti'),
    ('DMA', 'Dominica'),
    ('DOM', 'Dominican Republic'),
    ('ECU', 'Ecuador'),
    ('EGY', 'Egypt'),
    ('SLV', 'El Salvador'),
    ('GNQ', 'Equatorial Guinea'),
    ('ERI', 'Eritrea'),
    ('EST', 'Estonia'),
    ('SWZ', 'Eswatini'),
    ('ETH', 'Ethiopia'),
    ('FJI', 'Fiji'),
    ('FIN', 'Finland'),
    ('FRA', 'France'),
    ('GAB', 'Gabon'),
    ('GMB', 'Gambia'),
    ('GEO', 'Georgia'),
    ('DEU', 'Germany'),
    ('GHA', 'Ghana'),
    ('GRC', 'Greece'),
    ('GRD', 'Grenada'),
    ('GTM', 'Guatemala'),
    ('GIN', 'Guinea'),
    ('GNB', 'Guinea-Bissau'),
    ('GUY', 'Guyana'),
    ('HTI', 'Haiti'),
    ('HND', 'Honduras'),
    ('HUN', 'Hungary'),
    ('ISL', 'Iceland'),
    ('IND', 'India'),
    ('IDN', 'Indonesia'),
    ('IRN', 'Iran (Islamic Republic of)'),
    ('IRQ', 'Iraq'),
    ('IRL', 'Ireland'),
    ('ISR', 'Israel'),
    ('ITA', 'Italy'),
    ('JAM', 'Jamaica'),
    ('JPN', 'Japan'),
    ('JOR', 'Jordan'),
    ('KAZ', 'Kazakhstan'),
    ('KEN', 'Kenya'),
    ('KIR', 'Kiribati'),
    ('KWT', 'Kuwait'),
    ('KGZ', 'Kyrgyzstan'),
    ('LAO', "Lao People's Democratic Republic"),
    ('LVA', 'Latvia'),
    ('LBN', 'Lebanon'),
    ('LSO', 'Lesotho'),
    ('LBR', 'Liberia'),
    ('LBY', 'Libya'),
    ('LIE', 'Liechtenstein'),
    ('LTU', 'Lithuania'),
    ('LUX', 'Luxembourg'),
    ('MDG', 'Madagascar'),
    ('MWI', 'Malawi'),
    ('MYS', 'Malaysia'),
    ('MDV', 'Maldives'),
    ('MLI', 'Mali'),
    ('MLT', 'Malta'),
    ('MHL', 'Marshall Islands'),
    ('MRT', 'Mauritania'),
    ('MUS', 'Mauritius'),
    ('MEX', 'Mexico'),
    ('FSM', 'Micronesia (Federated States of)'),
    ('MCO', 'Monaco'),
    ('MNG', 'Mongolia'),
    ('MNE', 'Montenegro'),
    ('MAR', 'Morocco'),
    ('MOZ', 'Mozambique'),
    ('MMR', 'Myanmar'),
    ('NAM', 'Namibia'),
    ('NRU', 'Nauru'),
    ('NPL', 'Nepal'),
    ('NLD', 'Netherlands'),
    ('NZL', 'New Zealand'),
    ('NIC', 'Nicaragua'),
    ('NER', 'Niger'),
    ('NGA', 'Nigeria'),
    ('PRK', "Democratic People's Republic of Korea"),
    ('MKD', 'North Macedonia'),
    ('NOR', 'Norway'),
    ('OMN', 'Oman'),
    ('PAK', 'Pakistan'),
    ('PLW', 'Palau'),
    ('PAN', 'Panama'),
    ('PNG', 'Papua New Guinea'),
    ('PRY', 'Paraguay'),
    ('PER', 'Peru'),
    ('PHL', 'Philippines'),
    ('POL', 'Poland'),
    ('PRT', 'Portugal'),
    ('QAT', 'Qatar'),
    ('KOR', 'Republic of Korea'),
    ('MDA', 'Republic of Moldova'),
    ('ROU', 'Romania'),
    ('RUS', 'Russian Federation'),
    ('RWA', 'Rwanda'),
    ('KNA', 'Saint Kitts and Nevis'),
    ('LCA', 'Saint Lucia'),
    ('VCT', 'Saint Vincent and the Grenadines'),
    ('WSM', 'Samoa'),
    ('SMR', 'San Marino'),
    ('STP', 'Sao Tome and Principe'),
    ('SAU', 'Saudi Arabia'),
    ('SEN', 'Senegal'),
    ('SRB', 'Serbia'),
    ('SYC', 'Seychelles'),
    ('SLE', 'Sierra Leone'),
    ('SGP', 'Singapore'),
    ('SVK', 'Slovakia'),
    ('SVN', 'Slovenia'),
    ('SLB', 'Solomon Islands'),
    ('SOM', 'Somalia'),
    ('ZAF', 'South Africa'),
    ('SSD', 'South Sudan'),
    ('ESP', 'Spain'),
    ('LKA', 'Sri Lanka'),
    ('SDN', 'Sudan'),
    ('SUR', 'Suriname'),
    ('SWE', 'Sweden'),
    ('CHE', 'Switzerland'),
    ('SYR', 'Syrian Arab Republic'),
    ('TJK', 'Tajikistan'),
    ('THA', 'Thailand'),
    ('TLS', 'Timor-Leste'),
    ('TGO', 'Togo'),
    ('TON', 'Tonga'),
    ('TTO', 'Trinidad and Tobago'),
    ('TUN', 'Tunisia'),
    ('TUR', 'Turkey'),
    ('TKM', 'Turkmenistan'),
    ('TUV', 'Tuvalu'),
    ('UGA', 'Uganda'),
    ('UKR', 'Ukraine'),
    ('ARE', 'United Arab Emirates'),
    ('GBR', 'United Kingdom of Great Britain and Northern Ireland'),
    ('TZA', 'United Republic of Tanzania'),
    ('USA', 'United States of America'),
    ('URY', 'Uruguay'),
    ('UZB', 'Uzbekistan'),
    ('VUT', 'Vanuatu'),
    ('VEN', 'Venezuela (Bolivarian Republic of)'),
    ('VNM', 'Viet Nam'),
    ('YEM', 'Yemen'),
    ('ZMB', 'Zambia'),
    ('ZWE', 'Zimbabwe'),
]


LANGUAGES_CHOICES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('zh', 'Chinese'),
    ('ru', 'Russian'),
    ('ar', 'Arabic'),
    ('ja', 'Japanese'),
    ('pt', 'Portuguese'),
    ('bn', 'Bengali'),
    ('pa', 'Punjabi'),
    ('ja', 'Japanese'),
    ('ko', 'Korean'),
    ('vi', 'Vietnamese'),
    ('it', 'Italian'),
    ('th', 'Thai'),
    ('tr', 'Turkish'),
    ('el', 'Greek'),
    ('nl', 'Dutch'),
    ('pl', 'Polish'),
    ('uk', 'Ukrainian'),
    ('ro', 'Romanian'),
    ('hu', 'Hungarian'),
    ('cs', 'Czech'),
    ('sv', 'Swedish'),
    ('fi', 'Finnish'),
    ('da', 'Danish'),
    ('no', 'Norwegian'),
    ('he', 'Hebrew'),
    ('id', 'Indonesian'),
    ('ms', 'Malay'),
    ('tl', 'Tagalog'),
    ('sw', 'Swahili'),
    ('hi', 'Hindi'),
    ('gu', 'Gujarati'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('ml', 'Malayalam'),
    ('kn', 'Kannada'),
    ('mr', 'Marathi'),
    ('bn', 'Bengali'),
    ('pa', 'Punjabi'),
    ('ur', 'Urdu'),
    ('fa', 'Persian'),
    ('sd', 'Sindhi'),
    ('bh', 'Bihari'),
    ('ne', 'Nepali'),
    ('si', 'Sinhalese'),
    ('lv', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('et', 'Estonian'),
    ('ka', 'Georgian'),
    ('hy', 'Armenian'),
    ('az', 'Azerbaijani'),
    ('kk', 'Kazakh'),
    ('uz', 'Uzbek'),
    ('tk', 'Turkmen'),
    ('ky', 'Kyrgyz'),
    ('tg', 'Tajik'),
    ('ur', 'Urdu'),
    ('ps', 'Pashto'),
    ('sd', 'Sindhi'),
    ('dv', 'Dhivehi'),
    ('ug', 'Uighur'),
    ('bo', 'Tibetan'),
    ('dz', 'Dzongkha'),
    ('my', 'Burmese'),
    ('km', 'Khmer'),
    ('lo', 'Lao'),
    ('th', 'Thai'),
    ('vi', 'Vietnamese'),
    ('tl', 'Tagalog'),
    ('mg', 'Malagasy'),
    ('sn', 'Shona'),
    ('am', 'Amharic'),
    ('ti', 'Tigrinya'),
    ('om', 'Oromo'),
    ('so', 'Somali'),
    ('ig', 'Igbo'),
    ('yo', 'Yoruba'),
    ('ha', 'Hausa'),
    ('sw', 'Swahili'),
    ('zu', 'Zulu'),
    ('xh', 'Xhosa'),
    ('st', 'Southern Sotho'),
    ('tn', 'Tswana'),
    ('ts', 'Tsonga'),
    ('ss', 'Swati'),
    ('nr', 'Northern Ndebele'),
    ('nd', 'Southern Ndebele'),
    ('sn', 'Shona'),
    ('chy', 'Cheyenne'),
    ('arw', 'Arawakan'),
    ('paa', 'Papuan'),
    ('afr', 'Afrikaans'),
    ('amh', 'Amharic'),
    ('arc', 'Aramaic'),
    ('bas', 'Basa'),
    ('bem', 'Bemba'),
    ('bej', 'Beja'),
    ('bis', 'Bislama'),
    ('bua', 'Buriat'),
    ('car', 'Carib'),
    ('ceb', 'Cebuano'),
    ('chk', 'Chuukese'),
    ('cor', 'Cornish'),
    ('cos', 'Corsican'),
    ('div', 'Divehi'),
    ('fij', 'Fijian'),
    ('fur', 'Friulian'),
    ('frr', 'Frisian'),
    ('gaa', 'Ga'),
    ('glg', 'Galician'),
    ('got', 'Gothic'),
    ('haw', 'Hawaiian'),
    ('iku', 'Inuktitut'),
    ('ibo', 'Igbo'),
    ('ilo', 'Iloko'),
    ('inh', 'Ingush'),
    ('jpn', 'Japanese'),
    ('kal', 'Kalaallisut'),
    ('kik', 'Kikuyu'),
    ('kin', 'Kinyarwanda'),
    ('kir', 'Kirghiz'),
    ('kon', 'Kongo'),
    ('kor', 'Korean'),
    ('kua', 'Kuanyama'),
    ('kum', 'Kumyk'),
    ('kur', 'Kurdish'),
    ('lez', 'Lezghian'),
    ('lug', 'Luganda'),
    ('lua', 'Luba-Kasai'),
    ('luo', 'Luo (Kenya and Tanzania)'),
    ('luy', 'Luyia'),
    ('mdf', 'Moksha'),
    ('mhr', 'Mari (Russia)'),
    ('mfe', 'Morisyen'),
    ('min', 'Minangkabau'),
    ('moh', 'Mohawk'),
    ('nan', 'Min Nan Chinese'),
    ('nap', 'Neapolitan'),
    ('ndo', 'Ndonga'),
    ('nso', 'Northern Sotho'),
    ('nyo', 'Nyoro'),
    ('oci', 'Occitan'),
    ('olo', 'Livvi-Karelian'),
    ('orm', 'Oromo'),
    ('pag', 'Pangasinan'),
    ('pam', 'Kapampangan'),
    ('pap', 'Papiamento'),
    ('pcd', 'Picard'),
    ('pdc', 'Pennsylvania German'),
    ('pnb', 'Western Punjabi'),
    ('ppl', 'Pipil'),
    ('quc', 'K iche'),
    ('roh', 'Romansh'),
    ('rue', 'Rusyn'),
    ('sah', 'Yakut'),
    ('scn', 'Sicilian'),
    ('sco', 'Scots'),
    ('sma', 'Southern Sami'),
    ('smj', 'Lule Sami'),
    ('smn', 'Inari Sami'),
    ('sms', 'Skolt Sami'),
    ('son', 'Songhai'),
    ('sot', 'Sotho'),
    ('suk', 'Sukuma'),
    ('sus', 'Susu'),
    ('syc', 'Classical Syriac'),
    ('syr', 'Syriac'),
    ('tet', 'Tetum'),
    ('tig', 'Tigre'),
    ('tiv', 'Tiv'),
    ('tkl', 'Tokelauan'),
    ('tli', 'Tlingit'),
    ('tpi', 'Tok Pisin'),
    ('tum', 'Tumbuka'),
    ('tvl', 'Tuvaluan'),
    ('tyv', 'Tuvinian'),
    ('udm', 'Udmurt'),
    ('vep', 'Veps'),
    ('vls', 'West Flemish'),
    ('war', 'Waray'),
    ('wln', 'Walloon'),
    ('xal', 'Kalmyk'),
    ('yid', 'Yiddish'),
    ('yor', 'Yoruba'),
    ('zap', 'Zapotec'),
    ('zul', 'Zulu'),
]